---
title: "Volunteered"
author: "TBD"
site: bookdown::bookdown_site
documentclass: book
output:
  bookdown::gitbook: default
  #bookdown::pdf_book: default
---

# Barnacles

This is our first field survey. We're honoured, I think, to be given this chance without an older hand here to instruct us. Trusted, how easily we've wielded the mesh in training exercises, how easy it felt to diagnose the patterns and textures, in a quiet room. I try to recall that sense of focused calm. Just as it felt in training. A flake falls with a soft hiss and is dissolved into the sludge at our feet. There's a smell that's hard to connect with recollection. 

Xzrybt stoops, about to press a section of the fine mesh against the base of the extrusion. Removes a glove and hesitantly runs the pads of a finger against the surface. "Almost furred", Xzrybt ponders. "Feel this bit ... you'd expect it to be brittle, but", pressing more definitely, "it doesn't come away". We don't recognise it. I let out a murmur of indulgence and impatience; the mesh can recognise it for us. We can learn on the job, we need to show we're trusted, not hang about wasting words speculating on the nature of the job. The mesh is fine enough not to snag on the inexplicable surface. It pulses briefly with a bluish-pink as it hardens from more of a gel into more of a wire, as we take a reading.

...

The flakes start falling faster. I reach out and catch some, watch them not quite dissolve. A residue finer than our mesh will catch. Xzrybt, lifting their focus away, moves over and laughs. Runs a finger across the sulphurous powder caught in my palm. "Too bad. Too fine a texture... listen," a solemn pause as we try to hear the air. Xzrybt turns back towards the boulder-like, shell-like structure that is the object of our survey.

Turns back, and pauses. Hesitates, and seems to snag. We both look down at the accretion as they wrench themselves free. A shallow indentation, either a footprint or a canyon. As the flakes accumulate, the ground begins to take on a gel-like texture. I try to recall that sense of focused calm. A flick at the corner of the mesh restores it to a gel-like texture. It drapes easily over the next part of the extrusion. I check our vitals, then our estimates. We should still be fine, there's nothing too unexpected; we'll be rewarded with a better job. Need to climb up to reach the top of the structure, the next to final section. I turn, looking for a shoulder up.

Xzybrt is knee-deep, now, in the powdery gel. It looks like they're sinking, but it's simply the surface rising around them. With a half smile they plunge in an ungloved hand, feeling the resistance, the extent of the motion. I hum impatience, we are here to measure what we are sent to measure. "A hand here, please, if we have time later..." and I flick the corner of the mesh to take the final measure. But it doesn't come away. I can't make out the flakes now, as they fall too densely. 

A signal hum of resignation or acceptance. We've taken our readings, we should get an uplift from the next field survey. We've nothing to signal with, all we can do is wait. I reach out with a free hand towards Xzybrt's shoulder, wanting to feel reassured by offering reassurance. I feel a fuzzed hardness that ought to be brittle, but isn't. Where there should be a tone, is only a soft hiss of almost-silence. I try to recall. My hand doesn't come away.  
